/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acrcloud_utils_ACRCloudExtrTool */

#ifndef _Included_com_acrcloud_utils_ACRCloudExtrTool
#define _Included_com_acrcloud_utils_ACRCloudExtrTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_create_fingerprint_by_file
 * Signature: (Ljava/lang/String;IIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1create_1fingerprint_1by_1file
  (JNIEnv *, jclass, jstring, jint, jint, jboolean);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_create_humming_fingerprint_by_file
 * Signature: (Ljava/lang/String;II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1create_1humming_1fingerprint_1by_1file
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_create_fingerprint_by_filebuffer
 * Signature: ([BIIIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1create_1fingerprint_1by_1filebuffer
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jboolean);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_create_humming_fingerprint_by_filebuffer
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1create_1humming_1fingerprint_1by_1filebuffer
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_create_fingerprint
 * Signature: ([BIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1create_1fingerprint
  (JNIEnv *, jclass, jbyteArray, jint, jboolean);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_create_humming_fingerprint
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1create_1humming_1fingerprint
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_decode_audio_by_file
 * Signature: (Ljava/lang/String;II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1decode_1audio_1by_1file
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_decode_audio_by_filebuffer
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1decode_1audio_1by_1filebuffer
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_set_debug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1set_1debug
  (JNIEnv *, jclass);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_get_duration_ms_by_file
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1get_1duration_1ms_1by_1file
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_get_duration_ms_by_filebuffer
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1get_1duration_1ms_1by_1filebuffer
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_acrcloud_utils_ACRCloudExtrTool
 * Method:    native_get_doc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_acrcloud_utils_ACRCloudExtrTool_native_1get_1doc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
